#!/usr/bin/env python
import sys, os
import ydisk

YD_APP_ID = 'cb76e6135dc34947bcf7620e1ab62e54'
YD_APP_SECRET = 'e4dba0141d734e1d89a5333c26a44f46'

def main():
    if len(sys.argv) < 2:
        sys.stderr.write('No filename given\n')
        sys.exit(-2)
    key = ydisk.getKey(YD_APP_ID, YD_APP_SECRET)
    api = ydisk.DiskAPI(key)
    api.mkdir('/JustShared')

    for fname in sys.argv[1:]:
        if os.path.isfile(fname):
            fname = sys.argv[1]
            newname = '/JustShared/' + os.path.basename(fname)
            try:
                api.put(newname, open(fname, 'r').read())
                print api.publish(newname)
            except Exception, e:
                sys.stderr.write('Something wrong with %s\n%s\n' % (fname, e))
                sys.exit(-3)
        else:
            sys.stderr.write('No such file %s\n' % fname)
            sys.exit(-4)


if __name__ == '__main__':
    main()
